import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import ActiveSectionContextProvider from "@/Context/active-session-context";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="max-w-screen flex flex-col overflow-x-hidden"
      >
        <ActiveSectionContextProvider>
          {children}
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
